on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 3
          delete_tags: true
          delete_prerelease_only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
