name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: tap
        run: brew tap alteredtech/test-tap -v
      - name: show brew things
        run: |
          echo $(brew --repo)
          cd $(brew --repo)
          ls
          cd Library
          ls
          cd Taps
          ls

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: brew
          path: /usr/local/Homebrew/Library/Taps/alteredtech
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: brew
          path: jamf
      - name: move
        run: mv jamf /usr/local/Homebrew/Library/Taps/

      - name: list
        run: ls /usr/local/Homebrew/Library/Taps/
