name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew tap alteredtech/test-tap
        brew install random-number