name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install dependencies
      run: |
        brew update
        brew list
        brew install openjpeg freetype
    - name: Install tap and formula
      run: |
        brew tap alteredtech/test-tap
        brew install random-number

    - name: Upload homebrew log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: homebrew-log
        path: /Users/runner/Library/Logs/Homebrew/random-number
        retention-days: 5
