name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: tap
        run: brew tap alteredtech/test-tap -v
      - name: show brew things
        run: |
          echo $(brew --repo)
          cd $(brew --repo)
          ls
          cd Library
          ls
          cd Taps
          ls

      - name: script
        run: |
          for file in $(ls /opt/homebrew/Library/Taps/alteredtech); do
            echo $file
          done