name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: update brew
      run: brew update
    - name: remove unused formula
      run: brew autoremove

    - name: List all installed formulae
      run: brew list
    
    - name: Install dependencies
      run: brew install mozjpeg 
    
    - name: Install tap and formula
      run: |
        brew tap alteredtech/test-tap
        brew install random-number@9

    - name: Installed brew formulae
      if: always()
      run: |
        brew list

    - name: Upload homebrew log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: homebrew-log
        path: /Users/runner/Library/Logs/Homebrew/random-number
        retention-days: 5
