name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: tap
        run: brew tap alteredtech/test-tap -v
      - name: show brew things
        run: |
          echo $(brew --repo)
          cd $(brew --repo)
          ls
          cd Library
          ls
          cd Taps
          ls

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: brew
          path: /usr/local/Homebrew/Library/Taps/alteredtech
