name: Mac Homebrew Install
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: tap
        run: brew tap alteredtech/test-tap -v
      - name: show brew things
        run: |
          echo $(brew --repo)
          cd $(brew --repo)
          ls
          cd Library
          ls
          cd Taps
          ls

      - name: upload
        if: ${{matrix.os != 'macos-14'}}
        uses: actions/upload-artifact@v4
        with:
          name: brew-${{matrix.os}}
          path: /usr/local/Homebrew/Library/Taps/alteredtech
      - name: upload
        if: ${{matrix.os == 'macos-14'}}
        uses: actions/upload-artifact@v4
        with:
          name: brew-${{matrix.os}}
          path: /opt/homebrew/Library/Taps/alteredtech