# .github/workflows/release.yaml

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      sha256: ${{ steps.shasum.outputs.sha256 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2
      - name: Ensure pip is installed
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref}}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
      - name: Pip Requirements file
        run: |
          sudo apt-get install python3-pip
          pip install pipenv requests
          pipenv install
          pipenv run pip freeze > requirements.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: requirements
          path: requirements.txt
          retention-days: 1
      - name: Tarball for release
        run: |
          mkdir dist
          tar -czvf dist/random-number-release.tar.gz scripts
      - name: Create resource file
        id: create_resource
        run: |
          ls
          chmod +x ./pypackage_convert.py
          python ./pypackage_convert.py > resources.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brew-resources
          path: resources.txt
          retention-days: 1
      - name: SHAsum
        id: shasum
        run: |
          cd dist
          shasum -a 256 random-number-release.tar.gz > shasum-random-number-release
          cat shasum-random-number-release|cut -c1-64
          shasum=$(cat shasum-random-number-release|cut -c1-64)
          echo "sha256=${shasum}" >> "$GITHUB_OUTPUT"
      - name: Upload tar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
  update-homebrew:
    name: Update Homebrew
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: brew-resources
          path: resources.txt
      - name: Clone Homebrew
        env:
          SHA: ${{ needs.build.outputs.sha256 }}
        run: |
          cat resources.txt
          git config --global user.email "michael@einreinhof.com"
          git config --global user.name "${{ github.actor }}"
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.HOMEBREW_DEPLOY_SSH }}'
          git clone git@github.com:alteredtech/homebrew-test-tap.git homebrew
          ls
          cd homebrew
          cat ../resources.txt > tools/resources.txt
          cat <<EOF > tools/release.json
          {
            "version": "${{ github.ref_name }}",
            "sha256": "$SHA"
          }
          EOF
          git add tools/
          git commit -m 'Another Tools release ${{ github.ref_name }}'
          git push