name: Test
on: workflow_dispatch
jobs:
    tests:
        name: Test Develop Brew formula
        runs-on: ubuntu-latest
        steps: 
        # Install Homebrew on Linux
        - name: Set up Homebrew
          run: |
            sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get install build-essential procps curl file git libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew --version
        # Tap the Homebrew Formula
        - name: tap brew
          run: |
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew tap alteredtech/test-tap
        # Install the Formula and output the log to a file
        - name: install formula
          run: |
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew update && brew install random-number@9
        - name: brew list formula
          if: always()
          run: |
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew list
        # Upload homebrew log
        - name: Upload homebrew log
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: homebrew-log
            path: /home/runner/.cache/Homebrew/Logs/random-number@9
            retention-days: 5
